CREATE TABLE `greeting` (
  `id`   BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `date` BIGINT(20)   NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 83
  DEFAULT CHARSET = utf8;